# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Setup Terraform
      uess: hashicorp/setup-terraform@v1
      with:
        cli_config_credentials_token: ${{secrets.TF_API_TOKEN }}
        
    - name: Terraform Init
      run: terraform init
      
    - name Terraform Format
      run: terraform fmt -check
      
    - name: Terraform Plan
      run: terraform plan
    
    - name: Terraform Apply
      run: terraform apply -auto-approve
