name: CI
#update 1
#on: 
   #release:
   #  types: # This configuration does not affect the page_build event above
   #    - created
   
on:
  push:
    branches:
    - master
  pull_request:
     
env:
  somevar: 'lastvar'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
    - name: Is variable exported?
        run:|
          echo "${{ env.somevar }}
